stages:
  select_samples:
    cmd: papermill -f parameters/select_samples.yaml  --progress-bar --report-mode
      notebooks/select_samples.ipynb data/output/notebooks/select_samples.ipynb
    deps:
      - parameters/select_samples.yaml
      - data/input/genes/by_animal_class
      - data/input/species.tsv
      - data/input/samples.tsv
      - data/input/total_mtDNA_base_composition.csv
      - notebooks/select_samples.ipynb
    outs:
      - data/interim/selected/species.tsv
      - data/interim/selected/samples.tsv
      - data/interim/selected/genes.tsv
      - data/interim/selected/expressions.tsv
      - data/interim/selected/genes_meta.tsv
      - data/output/counts/species_sample_count.tsv
      - data/output/counts/tissue_sample_count.tsv
      - data/output/counts/species_tissue_sample_count.tsv
      - data/output/notebooks/select_samples.ipynb
  tune:
    cmd: python tune.py
    deps:
        - data/interim/selected/species.tsv
        - data/interim/selected/samples.tsv
        - data/interim/selected/genes.tsv
        - data/interim/selected/expressions.tsv
        - data/interim/selected/genes_meta.tsv
    outs:
        #- data/output/notebooks/tuning.ipynb
        - data/output/optimization/study.sqlite
    metrics:
        - data/output/optimization/parameters.json
        - data/output/optimization/metrics.tsv
  shap_selection:
    cmd: papermill -f parameters/shap_selection.yaml  --progress-bar --report-mode
      notebooks/shap_selection.ipynb data/output/notebooks/shap_selection.ipynb
    deps:
      - parameters/shap_selection.yaml
      - data/interim/selected/species.tsv
      - data/interim/selected/samples.tsv
      - data/interim/selected/genes.tsv
      - data/interim/selected/expressions.tsv
      - data/interim/selected/genes_meta.tsv
    outs:
      - data/output/notebooks/shap_selection.ipynb
  results_intersections:
    cmd: papermill -f parameters/results_intersections.yaml  --progress-bar --report-mode
      notebooks/results_intersections.ipynb data/output/notebooks/results_intersections.ipynb
    deps:
      - parameters/results_intersections.yaml
      - data/output/external/causality
      - data/output/external/linear
      - data/output/external/shap
      - data/output/external/causality/causal_relations_5_tissues_anton_species_5_bootstraps.csv
    outs:
      - data/output/notebooks/results_intersections.ipynb
      - data/output/intersections/genage_human_intersections.tsv
      - data/output/intersections/genage_model_intersections.tsv
      - data/output/intersections/intersections_5_and_7.tsv
      - data/output/intersections/intersections.tsv
      - data/output/intersections/new_old_comparison.tsv