stages:
  select_samples:
    cmd: papermill -f parameters/select_samples.yaml  --progress-bar --report-mode
      notebooks/select_samples.ipynb data/output/notebooks/select_samples.ipynb
    deps:
      - parameters/select_samples.yaml
      - data/input/genes/by_animal_class
      - data/input/species.tsv
      - data/input/samples.tsv
      - data/input/total_mtDNA_base_composition.csv
      - notebooks/select_samples.ipynb
    outs:
      - data/interim/selected/gestation_days
      - data/interim/selected/lifespan
      - data/interim/selected/mass_kg
      - data/interim/selected/metabolic_rate
      - data/interim/selected/mtGC
      - data/interim/selected/temperature
      - data/output/counts/species_sample_count.tsv
      - data/output/counts/tissue_sample_count.tsv
      - data/output/counts/species_tissue_sample_count.tsv
      - data/output/notebooks/select_samples.ipynb
  stage_one:
    cmd: papermill -f parameters/stage_one_shap_selection.yaml  --progress-bar --report-mode
      notebooks/stage_one_shap_selection.ipynb data/output/notebooks/stage_one_shap_selection.ipynb
    deps:
      - parameters/stage_one_shap_selection.yaml
      - data/interim/optimization/gestation_days.sqlite
      - data/interim/optimization/lifespan.sqlite
      - data/interim/optimization/mass_kg.sqlite
      - data/interim/optimization/metabolic_rate.sqlite
      - data/interim/optimization/mtGC.sqlite
      - data/interim/optimization/temperature.sqlite
    outs:
      #- data/output/notebooks/stage_one_shap_selection.ipynb
      - data/interim/stage_1/results_concatenated.tsv
      - data/interim/stage_1/partitions
      - data/interim/stage_2/input
      - data/output/plots/stage_one_summary_lifespan.svg
      - data/output/plots/stage_two_untuned_summary_lifespan.svg
      - data/output/stage_1/gestation_days_selected.tsv
      - data/output/stage_1/mass_kg_selected.tsv
      - data/output/stage_1/mtGC_selected.tsv
      - data/output/stage_1/lifespan_selected.tsv
      - data/output/stage_1/metabolic_rate_selected.tsv
      - data/output/stage_1/temperature_selected.tsv
  stage_two:
    cmd: papermill -f parameters/stage_two_shap_selection.yaml  --progress-bar --report-mode
      notebooks/stage_two_shap_selection.ipynb data/output/notebooks/stage_two_shap_selection.ipynb
    deps:
      - data/interim/stage_1/results_concatenated.tsv
      - data/interim/optimization/lifespan.sqlite
      - data/interim/stage_2/input
    outs:
      - data/interim/stage_2/partitions
      - data/output/stage_2/lifespan.tsv
      - data/output/plots/stage_two_summary_lifespan.svg
      - data/output/plots/stage_two_decision_lifespan.svg
      #  - data/output/notebooks/stage_two_shap_selection.ipynb
  tune:
    cmd: python tune.py
    params:
      - parameters/tune.yaml:
          - trait
          - metrics
          - trials
          - folds
          - hold_outs
          - repeats
          - not_validated_species
          - threads
          - debug_local
    deps:
      - data/interim/selected/gestation_days
      - data/interim/selected/lifespan
      - data/interim/selected/mass_kg
      - data/interim/selected/metabolic_rate
      - data/interim/selected/mtGC
      - data/interim/selected/temperature
  results_intersections:
    cmd: papermill -f parameters/results_intersections.yaml  --progress-bar --report-mode
      notebooks/results_intersections.ipynb data/output/notebooks/results_intersections.ipynb
    deps:
      - parameters/results_intersections.yaml
      - data/output/external/causality
      - data/output/external/linear
      - data/output/external/shap
      - data/output/external/causality/causal_relations_5_tissues_anton_species_5_bootstraps.csv
    outs:
      - data/output/notebooks/results_intersections.ipynb
      - data/output/intersections/genage_human_intersections.tsv
      - data/output/intersections/genage_model_intersections.tsv
      - data/output/intersections/intersections_5_and_7.tsv
      - data/output/intersections/intersections.tsv
      - data/output/intersections/new_old_comparison.tsv
