name: yspecies
channels:
  - antonkulaga
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numba=0.55.2
  - jupyterlab=3.4.4
  - matplotlib=3.5.2
  - dvc=2.16.0
  - dvc-gdrive=2.16.0
  - papermill=2.3.4
  - scikit-learn=1.1.1
  - anaconda-client=1.10.0
  - conda-build=3.21.9
  - mamba=0.25.0
  - more-itertools=8.13.0
  - lightgbm=3.3.2
  - statsmodels=0.13.1
  - click=8.1.3
  - loguru=0.6.0
  - plotly=5.9.0
  - shap=0.41.0
  - optuna=2.10.1