name: yspecies
channels:
  - antonkulaga
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3.2.3
  - dvc=2.8.3
  - dvc-gdrive=2.8.3
  - papermill=2.3.3
  - scikit-learn=1.0.1
  - anaconda-client=1.9.0
  - conda-build=3.21.6
  - mamba=0.17.0
  - scikit-learn=1.0.1
  - more-itertools=8.11.0
  - lightgbm=3.2.1
  - statsmodels=0.13.1
  - click=8.0.3
  - loguru=0.5.3
  - plotly=5.3.1
  - shap=0.40.0
  - optuna=2.10.0