package:
  name: yspecies
  version: 0.1.0

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy>=1.18.5
    - scipy>=1.4.1
    - python>=3.7.6
    - future>=0.18.2
    - jsonpath-ng>=1.5.1
    - jsonschema>=3.2.0
    - matplotlib>=3.2.1
    - notebook>=6.0.3
    - pandas>=1.0.3
    - pathlib>=1.0.1
    - pydrive2>=1.4.13
    - scikit-learn>=0.22.2.post1
    - scipy>=1.4.1
    - seaborn>=0.10.1
    - shap>=0.35.0
    - tabulate>=0.8.7
    - lightgbm>=2.3.1
    - statsmodels>=0.11.1

test:
  imports:
    - yspecies

source:
  path: ../