package:
  name: yspecies
  version: 0.1.3
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
  - anaconda
requirements:
  build:
    - python
    - setuptools
  run:
    - numpy>=1.18.5
    - python>=3.8
    - future>=0.18.2
    - matplotlib>=3.2.1
    - notebook>=6.0.3
    - pandas>=1.0.5
    - pathlib>=1.0.1
    - dvc>=1.1.10
    - scikit-learn>=0.23.1
    - seaborn>=0.10.1
    - shap=0.35.0
    - tabulate=0.8.7
    - lightgbm=2.3.1
    - statsmodels>=0.11.1
    - conda-build>=3.18.11
test:
  imports:
    - yspecies

source:
  path: ../