package:
  name: yspecies
  version: 0.2.0
channels:
  - conda-forge
  - bioconda
  - defaults
requirements:
  build:
    - python=3.8
    - setuptools
  run:
    - numpy>=1.18.5
    - python=3.8
    - pandas>=1.0.5
    - more-itertools>=8.4.0
    - scikit-learn>=0.23.2
    - seaborn>=0.10.1
    - shap>=0.35.0
    - lightgbm>=2.3.1
    - statsmodels>=0.11.1
    - optuna>=2.0.0
test:
  imports:
    - yspecies

source:
  path: ../