package:
  name: yspecies
  version: 0.1.6
channels:
  - conda-forge
  - bioconda
  - defaults
requirements:
  build:
    - python=3.8
    - setuptools
  run:
    - numpy>=1.18.5
    - python=3.8
    - future>=0.18.2
    - matplotlib>=3.2.1
    - pandas>=1.0.5
    - pathlib>=1.0.1
    - scikit-learn>=0.23.1
    - seaborn>=0.10.1
    - shap>=0.35.0
    - lightgbm>=2.3.1
    - statsmodels>=0.11.1
test:
  imports:
    - yspecies

source:
  path: ../