package:
  name: yspecies
  version: 0.0.4

requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.7.6
    - future>=0.18.2
    - jsonpath-ng>=1.5.1
    - jsonschema>=3.2.0
    - jupyter_client>=6.1.3
    - jupyter_core>=4.6.3
    - jupyterlab>=2.1.1
    - matplotlib>=3.2.1
    - mypy_extensions>=0.4.3
    - notebook>=6.0.3
    - pandas>=1.0.3
    - papermill>=2.1.0
    - pathlib>=1.0.1
    - pydrive2>=1.4.13
    - scikit-bio>=0.5.6
    - scikit-learn>=0.22.2.post1
    - scipy>=1.4.1
    - seaborn>=0.10.1
    - shap>=0.35.0
    - tabulate>=0.8.7
    - lightgbm>=2.3.1
    - statsmodels>=0.11.1

test:
  imports:
    - yspecies

source:
  path: ../