#!/bin/bash -eu
usage() { echo "$0 usage:" && grep " .*)\ #" $0; exit 0; }
NO_CACHE_OPT=''
options=$(getopt -l "help,no-cache" -o "h" -a -- "$@")
eval set -- "$options"

while true; do
    case $1 in
        -h|--help) # Display help
            usage
            ;;
        --no-cache) # Disable cache
            NO_CACHE_OPT=' --ignore-build-cache'
        ;;
        --)
            shift
            break;;
    esac
    shift
done



pushd "."
set -x
MLV_PY_CMD_PATH="pipeline/scripts/mlvtools_1_extract_data.py"
MLV_PY_CMD_NAME="mlvtools_1_extract_data.py"

# META FILENAME, MODIFY IF DUPLICATE
MLV_DVC_META_FILENAME="./mlvtools_1_extract_data.dvc"

dvc run${NO_CACHE_OPT} --overwrite-dvcfile -f $MLV_DVC_META_FILENAME \
-o data/output/run.tsv
run = "sra:SRR1521445" \
pipeline/scripts/mlvtools_1_extract_data.py run


popd